---
abstract: 'is a Perl wrapper for the Foursqauare API.'
author:
  - 'Pavel Vlasov <fxzuz@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - foursquare
  - 4sq
  - www-foursquare
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Foursquare
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 2.5
  LWP: 6.01
  LWP::Protocol::https: 0
  URI: 0
  perl: 5.006
resources:
  homepage: http://fxzuz.github.com/WWW-Foursquare
  repository: https://github.com/fxzuz/WWW-Foursquare
version: 0.9903
